# **Python Numpy**
By James Sifuna, PhD

# Numpy

- Numpy is a python library.
- It is used for working with arrays.
- It is short for "Numerical Python"
- It aims to provide an array object that is up to 50x faster than traditional Python lists.

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))
print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.23.5


In [2]:
#Number of Dimensions
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5]) #1d- array
c = np.array([[1,2,3],[4,5,6]]) #2d-array
d = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# **NumPy Array Slicing**

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [4]:
print(arr[4:])

[5 6 7]


In [5]:
print(arr[:4])

[1 2 3 4]


In [ ]:
print(arr[-3:-1])

[5 6]


In [ ]:
print(arr[1:5:2])

[2 4]


In [ ]:
print(arr[::2])

[1 3 5 7]


In [ ]:
print(arr[0:2])

[1 2]


# **Numpy Array Copy vs view**

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

- The copy SHOULD NOT be affected by the changes made to the original array.

- The view SHOULD be affected by the changes made to the original array.

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [7]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [8]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


# Joining Numpy Arrays

In [9]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
arr6 = np.stack((arr1,arr2), axis = 1)
arr7 = np.hstack((arr1,arr2))
arr8 = np.vstack((arr1,arr2))
arr9 = np.dstack((arr1,arr2))

print(arr)

print("----------*********-----------")

print(arr6)

print("----------**********-----------")

print(arr7)

print("----------**********------------")

print(arr8)

print("----------**********-----------")

print(arr9)

[1 2 3 4 5 6]
----------*********-----------
[[1 4]
 [2 5]
 [3 6]]
----------**********-----------
[1 2 3 4 5 6]
----------**********------------
[[1 2 3]
 [4 5 6]]
----------**********-----------
[[[1 4]
  [2 5]
  [3 6]]]


# Searching Arrays

In [10]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

x1 = np.where(arr == 4) #To search an array, use the where() method
x2 = np.where(arr%2==0) #find the indexes where the values are even
x3 = np.where(arr%2==1) #find the indexes where the values are odd
x4 = np.searchsorted(arr,6) #the searchsorted() method is assumed to be used on sorted arrays.Find the indexes where the value 6 should be inserted.

print(x1)
print(x2)
print(x3)
print(x4)

(array([3]),)
(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)
5


# Sorting Arrays

sorting means putting elements in an ordered sequence.

In [11]:
import numpy as np

arr1 = np.array([3,2,0,1])
arr2 = np.array([[3,2,4],[5,0,1]])
arr3 = np.array(['banana','cherry','apple'])
arr4 = np.array([True,False,True])

print(np.sort(arr1))
print(np.sort(arr2))
print(np.sort(arr3))
print(np.sort(arr4))

[0 1 2 3]
[[2 3 4]
 [0 1 5]]
['apple' 'banana' 'cherry']
[False  True  True]
